"""booking_userid_id

Revision ID: 50251eaddbd1
Revises: 3be42d9cc1c4
Create Date: 2024-07-17 14:44:29.608804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50251eaddbd1'
down_revision: Union[str, None] = '3be42d9cc1c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('user_id', sa.String(length=50), nullable=False))
    op.create_foreign_key(None, 'payment', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.drop_column('payment', 'user_id')
    # ### end Alembic commands ###
