"""add_tour_guider_id_

Revision ID: 54b3c9ee9665
Revises: 69fa28fc5b20
Create Date: 2024-07-16 15:35:10.181740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54b3c9ee9665'
down_revision: Union[str, None] = '69fa28fc5b20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
