"""add_tour_guider

Revision ID: 69fa28fc5b20
Revises: cb1987f3fee3
Create Date: 2024-07-16 15:24:54.967706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69fa28fc5b20'
down_revision: Union[str, None] = 'cb1987f3fee3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('tour_guider', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tour_guider', 'is_deleted')
    op.drop_column('payment', 'is_deleted')
    # ### end Alembic commands ###
