"""tour_data_1

Revision ID: 8fa4b47c8042
Revises: 94bb9e0fd74d
Create Date: 2024-07-12 16:48:39.009867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fa4b47c8042'
down_revision: Union[str, None] = '94bb9e0fd74d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tours', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('tours', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('tours', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('tours', sa.Column('modified_at', sa.DateTime(), nullable=True))
    op.alter_column('tours', 'duration',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('tours', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tours', 'price',
               existing_type=sa.String(length=100),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('tours', 'duration',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('tours', 'modified_at')
    op.drop_column('tours', 'created_at')
    op.drop_column('tours', 'is_active')
    op.drop_column('tours', 'is_deleted')
    # ### end Alembic commands ###
