"""tour_data_relation

Revision ID: cb1987f3fee3
Revises: 624cec10e379
Create Date: 2024-07-12 18:24:09.112501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb1987f3fee3'
down_revision: Union[str, None] = '624cec10e379'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('booking', 'number_of_people',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('booking', 'total_price_per_person',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('booking', 'booking_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('booking', 'booking_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('booking', 'total_price_per_person',
               existing_type=sa.String(length=200),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('booking', 'number_of_people',
               existing_type=sa.String(length=200),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
